export const langaugeString = {
  english: {
    SignIn: "Sign In",
    SignUp: "Sign Up",
    FullName: "Full name",
    Email: "Email",
    Password: "Password",
    NewToNetflix: "New to Netflix?",
    AlreadyRegistered: "Already registered?",
    SignUpNow: "Sign up now",
    SignInNow: "Sign in now",
    WhatDoYouWantWatch: "What do you want watch?",
    Search: "Search",
    NowPlayingMovies: "Now Playing Movies",
    TopRated: "Top Rated",
    Popular: "Popular",
    Upcoming: "Upcoming",
    MoreInfo: "More Info",
    Play: "Play",
    Browse: "Browse",
    GPTSearch: "GPT Search",
    SignOut: "Sign Out",
  },
  hindi: {
    SignIn: "साइन इन करें",
    SignUp: "साइन अप करें",
    FullName: "पूरा नाम",
    Email: "ईमेल",
    Password: "पासवर्ड",
    NewToNetflix: "नेटफ्लिक्स पर नए हैं?",
    AlreadyRegistered: "पहले से रजिस्टर्ड हैं?",
    SignUpNow: "अभी साइन अप करें",
    SignInNow: "अब साइन इन करो",
    WhatDoYouWantWatch: "आप क्या देखना चाहते हैं?",
    Search: "खोज",
    NowPlayingMovies: "अभी फ़िल्में चल रही हैं",
    TopRated: "सर्वाधिक मानांकित",
    Popular: "लोकप्रिय",
    Upcoming: "आगामी",
    MoreInfo: "और जानकारी",
    Play: "प्ले",
    Browse: "ब्राउज़ करें",
    GPTSearch: "GPT खोज",
    SignOut: "साइन आउट",
  },
  marathi: {
    SignIn: "साइन इन करा",
    SignUp: "साइन अप करा",
    FullName: "पूर्ण नाव",
    Email: "ईमेल",
    Password: "पासवर्ड",
    NewToNetflix: "Netflix वर नवीन आहे?",
    AlreadyRegistered: "आधीच नोंदणी झाली आहे?",
    SignUpNow: "आत्ताच नोंदणी करा",
    SignInNow: "आता साइन इन करा",
    WhatDoYouWantWatch: "तुम्हाला काय पहायचे आहे?",
    Search: "शोधा",
    NowPlayingMovies: "आता चित्रपट चालत आहे",
    TopRated: "सर्वाधिक मानांकित",
    Popular: "लोकप्रिय",
    Upcoming: "आगामी",
    MoreInfo: "अधिक माहिती",
    Play: "प्ले",
    Browse: "ब्राउझ करा",
    GPTSearch: "GPT शोधा",
    SignOut: "साइन आउट",
  },
};

export const supportedLanguages = [
    {identifier: "english", name: "English"},
    {identifier: "hindi", name: "हिंदी"},
    {identifier: "marathi", name: "मराठी"},
]
